[tool.poetry]
name = "myYFinance"
version = "0.3.0"
description = "A robust Python class based taking stock data from yfinance and put them into dedicated dicts."
authors = ["oliverrudow <oliver.rudow@googlemail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
yfinance = "^1.4.1"
pandas = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"